version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

  settings:
    govet:
      disable:
        - shadow

  exclusions:
    presets:
      - common-false-positives
    paths:
      - vendor
      - third_party
      - testutil
      - docs
      - proto
      - scripts
      - simapp
      - ".*\\.pb\\.go$"
      - ".*\\.pb\\.gw\\.go$"
      - ".*\\.pulsar\\.go$"
      - ".*_test\\.go$"
    rules:
      - path: _test\.go
        linters:
          - gosec
          - goconst
          - gocyclo
          - errcheck
          - dupl
          - funlen
          - gocritic
      - path: \.pb\.go$
        linters:
          - all
      - path: \.pb\.gw\.go$
        linters:
          - all
      - path: \.pulsar\.go$
        linters:
          - all

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    paths:
      - vendor
      - third_party
      - testutil
      - docs
      - proto
      - scripts
      - simapp
      - ".*\\.pb\\.go$"
      - ".*\\.pb\\.gw\\.go$"
      - ".*\\.pulsar\\.go$"
      - ".*_test\\.go$"
