accounts:
  - name: alice
    coins: ["1000000000000ubze"]
  - name: bob
    coins: ["1000000000000ubze"]
validator:
  name: alice
  staked: "10000000000ubze"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000000000ubze"]
build:
  binary: "bzed"