accounts:
  - name: alice
    coins: ["1000000000000utestbze"]
  - name: bob
    coins: ["1000000000000utestbze"]
validator:
  name: alice
  staked: "10000000000utestbze"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000000000utestbze"]
build:
  binary: "bzed"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "utestbze"
    gov:
      voting_params:
        voting_period: "120s"
      deposit_params:
        min_deposit:
          -
            denom: "utestbze"
            amount: "1000000"
      tally_params:
        quorum: "0.00001"
        threshold: "0.001"
        veto_threshold: "0.01"
    cointrunk:
      params:
        anonArticleLimit: 5
        anonArticleCost:
          denom: "utestbze"
          amount: "25000000000"