accounts:
  - name: alice
    coins: ["1000000000000utestbze"]
  - name: bob
    coins: ["1000000000000utestbze"]
validator:
  name: alice
  staked: "10000000000utestbze"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000000000utestbze"]
build:
  binary: "bzed"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "utestbze"