// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bze/cointrunk/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAcceptedDomainRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAcceptedDomainRequest) Reset()         { *m = QueryAcceptedDomainRequest{} }
func (m *QueryAcceptedDomainRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAcceptedDomainRequest) ProtoMessage()    {}
func (*QueryAcceptedDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{2}
}
func (m *QueryAcceptedDomainRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAcceptedDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAcceptedDomainRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAcceptedDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAcceptedDomainRequest.Merge(m, src)
}
func (m *QueryAcceptedDomainRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAcceptedDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAcceptedDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAcceptedDomainRequest proto.InternalMessageInfo

func (m *QueryAcceptedDomainRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAcceptedDomainResponse struct {
	AcceptedDomain []AcceptedDomain    `protobuf:"bytes,1,rep,name=acceptedDomain,proto3" json:"acceptedDomain"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAcceptedDomainResponse) Reset()         { *m = QueryAcceptedDomainResponse{} }
func (m *QueryAcceptedDomainResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAcceptedDomainResponse) ProtoMessage()    {}
func (*QueryAcceptedDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{3}
}
func (m *QueryAcceptedDomainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAcceptedDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAcceptedDomainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAcceptedDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAcceptedDomainResponse.Merge(m, src)
}
func (m *QueryAcceptedDomainResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAcceptedDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAcceptedDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAcceptedDomainResponse proto.InternalMessageInfo

func (m *QueryAcceptedDomainResponse) GetAcceptedDomain() []AcceptedDomain {
	if m != nil {
		return m.AcceptedDomain
	}
	return nil
}

func (m *QueryAcceptedDomainResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPublisherRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPublisherRequest) Reset()         { *m = QueryPublisherRequest{} }
func (m *QueryPublisherRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPublisherRequest) ProtoMessage()    {}
func (*QueryPublisherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{4}
}
func (m *QueryPublisherRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPublisherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPublisherRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPublisherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPublisherRequest.Merge(m, src)
}
func (m *QueryPublisherRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPublisherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPublisherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPublisherRequest proto.InternalMessageInfo

func (m *QueryPublisherRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPublisherResponse struct {
	Publisher  []Publisher         `protobuf:"bytes,1,rep,name=publisher,proto3" json:"publisher"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPublisherResponse) Reset()         { *m = QueryPublisherResponse{} }
func (m *QueryPublisherResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPublisherResponse) ProtoMessage()    {}
func (*QueryPublisherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{5}
}
func (m *QueryPublisherResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPublisherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPublisherResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPublisherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPublisherResponse.Merge(m, src)
}
func (m *QueryPublisherResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPublisherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPublisherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPublisherResponse proto.InternalMessageInfo

func (m *QueryPublisherResponse) GetPublisher() []Publisher {
	if m != nil {
		return m.Publisher
	}
	return nil
}

func (m *QueryPublisherResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPublisherByIndexRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryPublisherByIndexRequest) Reset()         { *m = QueryPublisherByIndexRequest{} }
func (m *QueryPublisherByIndexRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPublisherByIndexRequest) ProtoMessage()    {}
func (*QueryPublisherByIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{6}
}
func (m *QueryPublisherByIndexRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPublisherByIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPublisherByIndexRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPublisherByIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPublisherByIndexRequest.Merge(m, src)
}
func (m *QueryPublisherByIndexRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPublisherByIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPublisherByIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPublisherByIndexRequest proto.InternalMessageInfo

func (m *QueryPublisherByIndexRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryPublisherByIndexResponse struct {
	Publisher Publisher `protobuf:"bytes,1,opt,name=publisher,proto3" json:"publisher"`
}

func (m *QueryPublisherByIndexResponse) Reset()         { *m = QueryPublisherByIndexResponse{} }
func (m *QueryPublisherByIndexResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPublisherByIndexResponse) ProtoMessage()    {}
func (*QueryPublisherByIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{7}
}
func (m *QueryPublisherByIndexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPublisherByIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPublisherByIndexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPublisherByIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPublisherByIndexResponse.Merge(m, src)
}
func (m *QueryPublisherByIndexResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPublisherByIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPublisherByIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPublisherByIndexResponse proto.InternalMessageInfo

func (m *QueryPublisherByIndexResponse) GetPublisher() Publisher {
	if m != nil {
		return m.Publisher
	}
	return Publisher{}
}

type QueryAllArticlesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllArticlesRequest) Reset()         { *m = QueryAllArticlesRequest{} }
func (m *QueryAllArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllArticlesRequest) ProtoMessage()    {}
func (*QueryAllArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{8}
}
func (m *QueryAllArticlesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllArticlesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllArticlesRequest.Merge(m, src)
}
func (m *QueryAllArticlesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllArticlesRequest proto.InternalMessageInfo

func (m *QueryAllArticlesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllArticlesResponse struct {
	Article    []Article           `protobuf:"bytes,1,rep,name=article,proto3" json:"article"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllArticlesResponse) Reset()         { *m = QueryAllArticlesResponse{} }
func (m *QueryAllArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllArticlesResponse) ProtoMessage()    {}
func (*QueryAllArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{9}
}
func (m *QueryAllArticlesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllArticlesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllArticlesResponse.Merge(m, src)
}
func (m *QueryAllArticlesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllArticlesResponse proto.InternalMessageInfo

func (m *QueryAllArticlesResponse) GetArticle() []Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func (m *QueryAllArticlesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAnonArticlesCountersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAnonArticlesCountersRequest) Reset()         { *m = QueryAllAnonArticlesCountersRequest{} }
func (m *QueryAllAnonArticlesCountersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAnonArticlesCountersRequest) ProtoMessage()    {}
func (*QueryAllAnonArticlesCountersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{10}
}
func (m *QueryAllAnonArticlesCountersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAnonArticlesCountersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAnonArticlesCountersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAnonArticlesCountersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAnonArticlesCountersRequest.Merge(m, src)
}
func (m *QueryAllAnonArticlesCountersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAnonArticlesCountersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAnonArticlesCountersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAnonArticlesCountersRequest proto.InternalMessageInfo

func (m *QueryAllAnonArticlesCountersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAnonArticlesCountersResponse struct {
	AnonArticlesCounters []AnonArticlesCounter `protobuf:"bytes,1,rep,name=AnonArticlesCounters,proto3" json:"AnonArticlesCounters"`
	Pagination           *query.PageResponse   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAnonArticlesCountersResponse) Reset()         { *m = QueryAllAnonArticlesCountersResponse{} }
func (m *QueryAllAnonArticlesCountersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAnonArticlesCountersResponse) ProtoMessage()    {}
func (*QueryAllAnonArticlesCountersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b58266f03569d710, []int{11}
}
func (m *QueryAllAnonArticlesCountersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAnonArticlesCountersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAnonArticlesCountersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAnonArticlesCountersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAnonArticlesCountersResponse.Merge(m, src)
}
func (m *QueryAllAnonArticlesCountersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAnonArticlesCountersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAnonArticlesCountersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAnonArticlesCountersResponse proto.InternalMessageInfo

func (m *QueryAllAnonArticlesCountersResponse) GetAnonArticlesCounters() []AnonArticlesCounter {
	if m != nil {
		return m.AnonArticlesCounters
	}
	return nil
}

func (m *QueryAllAnonArticlesCountersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "bze.cointrunk.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "bze.cointrunk.v1.QueryParamsResponse")
	proto.RegisterType((*QueryAcceptedDomainRequest)(nil), "bze.cointrunk.v1.QueryAcceptedDomainRequest")
	proto.RegisterType((*QueryAcceptedDomainResponse)(nil), "bze.cointrunk.v1.QueryAcceptedDomainResponse")
	proto.RegisterType((*QueryPublisherRequest)(nil), "bze.cointrunk.v1.QueryPublisherRequest")
	proto.RegisterType((*QueryPublisherResponse)(nil), "bze.cointrunk.v1.QueryPublisherResponse")
	proto.RegisterType((*QueryPublisherByIndexRequest)(nil), "bze.cointrunk.v1.QueryPublisherByIndexRequest")
	proto.RegisterType((*QueryPublisherByIndexResponse)(nil), "bze.cointrunk.v1.QueryPublisherByIndexResponse")
	proto.RegisterType((*QueryAllArticlesRequest)(nil), "bze.cointrunk.v1.QueryAllArticlesRequest")
	proto.RegisterType((*QueryAllArticlesResponse)(nil), "bze.cointrunk.v1.QueryAllArticlesResponse")
	proto.RegisterType((*QueryAllAnonArticlesCountersRequest)(nil), "bze.cointrunk.v1.QueryAllAnonArticlesCountersRequest")
	proto.RegisterType((*QueryAllAnonArticlesCountersResponse)(nil), "bze.cointrunk.v1.QueryAllAnonArticlesCountersResponse")
}

func init() { proto.RegisterFile("bze/cointrunk/v1/query.proto", fileDescriptor_b58266f03569d710) }

var fileDescriptor_b58266f03569d710 = []byte{
	// 777 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x4f, 0x13, 0x5b,
	0x14, 0xee, 0xe5, 0x3d, 0x20, 0x1c, 0x12, 0x42, 0xee, 0xeb, 0x7b, 0xf4, 0x0d, 0x65, 0xac, 0xc3,
	0x6f, 0x84, 0xb9, 0x29, 0x22, 0x89, 0x2b, 0x03, 0x1a, 0x7f, 0x2c, 0x34, 0xd8, 0xa5, 0x9b, 0x7a,
	0xdb, 0xde, 0x94, 0x89, 0xd3, 0xb9, 0x43, 0x67, 0x8a, 0x80, 0x71, 0x63, 0x5c, 0xb8, 0xd4, 0xb8,
	0x71, 0x65, 0x8c, 0x7f, 0x84, 0x4b, 0xd7, 0x2c, 0x49, 0xdc, 0xb8, 0x32, 0x06, 0xfc, 0x43, 0x4c,
	0xef, 0x9c, 0x29, 0x4c, 0x67, 0x86, 0x82, 0xe9, 0xae, 0xd3, 0xf3, 0x9d, 0x73, 0xbe, 0xf3, 0x9d,
	0x7b, 0xbf, 0x19, 0xc8, 0x57, 0x0e, 0x04, 0xab, 0x4a, 0xcb, 0xf1, 0x9b, 0x2d, 0xe7, 0x19, 0xdb,
	0x2d, 0xb2, 0x9d, 0x96, 0x68, 0xee, 0x9b, 0x6e, 0x53, 0xfa, 0x92, 0x8e, 0x57, 0x0e, 0x84, 0xd9,
	0x89, 0x9a, 0xbb, 0x45, 0x2d, 0x5b, 0x97, 0x75, 0xa9, 0x82, 0xac, 0xfd, 0x2b, 0xc0, 0x69, 0xf9,
	0xba, 0x94, 0x75, 0x5b, 0x30, 0xee, 0x5a, 0x8c, 0x3b, 0x8e, 0xf4, 0xb9, 0x6f, 0x49, 0xc7, 0xc3,
	0xe8, 0x52, 0x55, 0x7a, 0x0d, 0xe9, 0xb1, 0x0a, 0xf7, 0x44, 0x50, 0x9e, 0xed, 0x16, 0x2b, 0xc2,
	0xe7, 0x45, 0xe6, 0xf2, 0xba, 0xe5, 0x28, 0x30, 0x62, 0xa7, 0x62, 0x7c, 0x5c, 0xde, 0xe4, 0x8d,
	0xb0, 0xd4, 0x5c, 0x2c, 0xcc, 0xab, 0x55, 0xe1, 0xfa, 0xa2, 0x56, 0xae, 0xc9, 0x06, 0xb7, 0xc2,
	0x32, 0x85, 0x78, 0x99, 0x56, 0xc5, 0xb6, 0xbc, 0x6d, 0xd1, 0x44, 0x84, 0x1e, 0xaf, 0xd4, 0xf4,
	0xad, 0xaa, 0x2d, 0x30, 0xbe, 0x1c, 0x8f, 0x3b, 0xd2, 0x29, 0x23, 0xc8, 0x2b, 0x57, 0x65, 0xcb,
	0xf1, 0xc3, 0x6a, 0x46, 0x16, 0xe8, 0xe3, 0xf6, 0x60, 0x5b, 0x8a, 0x6c, 0x49, 0xec, 0xb4, 0x84,
	0xe7, 0x1b, 0x0f, 0xe1, 0x9f, 0xc8, 0xbf, 0x9e, 0x2b, 0x1d, 0x4f, 0xd0, 0x75, 0x18, 0x0a, 0x86,
	0xca, 0x91, 0x02, 0x59, 0x18, 0x5d, 0xcd, 0x99, 0xdd, 0x32, 0x9b, 0x41, 0xc6, 0xe6, 0xdf, 0x87,
	0x3f, 0xae, 0x64, 0x4a, 0x88, 0x36, 0x6a, 0xa0, 0xa9, 0x72, 0x1b, 0x38, 0xf2, 0x1d, 0x35, 0x31,
	0x36, 0xa3, 0x77, 0x01, 0x4e, 0xd5, 0xc4, 0xca, 0x73, 0x66, 0x20, 0xbd, 0xd9, 0x96, 0xde, 0x0c,
	0x36, 0x8b, 0xd2, 0x9b, 0x5b, 0xbc, 0x2e, 0x30, 0xb7, 0x74, 0x26, 0xd3, 0xf8, 0x42, 0x60, 0x32,
	0xb1, 0x0d, 0xb2, 0x7f, 0x04, 0x63, 0x3c, 0x12, 0xc9, 0x91, 0xc2, 0x5f, 0x0b, 0xa3, 0xab, 0x85,
	0xf8, 0x14, 0xd1, 0x0a, 0x38, 0x4d, 0x57, 0x36, 0xbd, 0x17, 0xe1, 0x3d, 0xa0, 0x78, 0xcf, 0xf7,
	0xe4, 0x1d, 0x90, 0x89, 0x10, 0x2f, 0xc3, 0xbf, 0x81, 0xda, 0xe1, 0xa6, 0xfb, 0xad, 0xcc, 0x67,
	0x02, 0xff, 0x75, 0x77, 0x40, 0x51, 0x6e, 0xc1, 0x48, 0xe7, 0x80, 0xa1, 0x1e, 0x93, 0x09, 0x5b,
	0x0d, 0x21, 0x28, 0xc5, 0x69, 0x4e, 0xff, 0x54, 0x58, 0x83, 0x7c, 0x94, 0xe3, 0xe6, 0xfe, 0x03,
	0xa7, 0x26, 0xf6, 0x42, 0x31, 0xb2, 0x30, 0x68, 0xb5, 0x9f, 0x95, 0x0e, 0x23, 0xa5, 0xe0, 0xc1,
	0x78, 0x0a, 0x53, 0x29, 0x59, 0xc9, 0x03, 0x92, 0xcb, 0x0e, 0x68, 0x70, 0x98, 0x08, 0x4e, 0x95,
	0x6d, 0x6f, 0xe0, 0x1d, 0x4a, 0xde, 0xcf, 0xc0, 0x1f, 0xef, 0xe7, 0x23, 0x81, 0x5c, 0xbc, 0x07,
	0x0e, 0x70, 0x13, 0x86, 0xf1, 0xee, 0xe2, 0x7e, 0xfe, 0x4f, 0x38, 0xaf, 0x01, 0x00, 0xc9, 0x87,
	0xf8, 0xfe, 0xed, 0xa6, 0x01, 0xd3, 0x1d, 0x7e, 0x8e, 0x74, 0x42, 0x8e, 0xb7, 0x03, 0x2b, 0xf1,
	0xfa, 0x7d, 0x5e, 0x8f, 0x08, 0xcc, 0x9c, 0xdf, 0x0f, 0xb5, 0x29, 0x43, 0x36, 0x29, 0x8e, 0x42,
	0xcd, 0x26, 0x08, 0x15, 0x47, 0xa3, 0x68, 0x89, 0x85, 0xfa, 0xa6, 0xe0, 0xea, 0xbb, 0x61, 0x18,
	0x54, 0x23, 0xd1, 0xe7, 0x30, 0x14, 0x98, 0x24, 0x9d, 0x89, 0xf3, 0x8b, 0x7b, 0xb1, 0x36, 0xdb,
	0x03, 0x15, 0x34, 0x33, 0x0a, 0xaf, 0xbe, 0xfd, 0x7a, 0x3f, 0xa0, 0xd1, 0x1c, 0x4b, 0x79, 0x11,
	0xd1, 0x0f, 0x04, 0xc6, 0xa2, 0xc6, 0x46, 0x97, 0x53, 0x6a, 0x27, 0x1a, 0xb5, 0xb6, 0x72, 0x41,
	0x34, 0x32, 0x5a, 0x54, 0x8c, 0xa6, 0xe9, 0x55, 0xd6, 0xeb, 0xdd, 0x47, 0x5f, 0x13, 0x18, 0xe9,
	0x5c, 0x41, 0x3a, 0x9f, 0x36, 0x71, 0x97, 0x3f, 0x6a, 0x0b, 0xbd, 0x81, 0xc8, 0x65, 0x46, 0x71,
	0xd1, 0x69, 0x9e, 0xa5, 0xbf, 0x5f, 0x3d, 0xfa, 0x89, 0xc0, 0x78, 0xb7, 0x91, 0x50, 0xb3, 0x57,
	0x93, 0xa8, 0x4f, 0x69, 0xec, 0xc2, 0x78, 0xe4, 0x76, 0x4d, 0x71, 0x9b, 0xa5, 0xd3, 0xe7, 0x70,
	0x63, 0x2f, 0x94, 0xdd, 0xbd, 0xa4, 0x6f, 0x08, 0x8c, 0x9e, 0x71, 0x09, 0xba, 0x98, 0xb6, 0x93,
	0x98, 0x5b, 0x69, 0x4b, 0x17, 0x81, 0x22, 0x27, 0x43, 0x71, 0xca, 0x53, 0x8d, 0xa5, 0x7d, 0x6d,
	0x78, 0xf4, 0x2b, 0x81, 0x89, 0x94, 0x0b, 0x4a, 0x6f, 0x9c, 0xd3, 0x2b, 0xdd, 0x40, 0xb4, 0xf5,
	0xcb, 0xa6, 0x21, 0xdd, 0x35, 0x45, 0xd7, 0xa4, 0xcb, 0x09, 0x74, 0x6d, 0xbb, 0x9c, 0xf8, 0x01,
	0xe4, 0x6d, 0xde, 0x3f, 0x3c, 0xd6, 0xc9, 0xd1, 0xb1, 0x4e, 0x7e, 0x1e, 0xeb, 0xe4, 0xed, 0x89,
	0x9e, 0x39, 0x3a, 0xd1, 0x33, 0xdf, 0x4f, 0xf4, 0xcc, 0x13, 0xb3, 0x6e, 0xf9, 0xdb, 0xad, 0x8a,
	0x59, 0x95, 0x8d, 0x76, 0xc5, 0x15, 0x6e, 0xbb, 0xdb, 0xdc, 0x17, 0x5c, 0x3d, 0xb1, 0xbd, 0x33,
	0x1d, 0xfc, 0x7d, 0x57, 0x78, 0x95, 0x21, 0xf5, 0x31, 0x75, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6d, 0x3e, 0x86, 0x30, 0x95, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of AcceptedDomain items.
	AcceptedDomain(ctx context.Context, in *QueryAcceptedDomainRequest, opts ...grpc.CallOption) (*QueryAcceptedDomainResponse, error)
	// Queries a list of Publisher items.
	Publisher(ctx context.Context, in *QueryPublisherRequest, opts ...grpc.CallOption) (*QueryPublisherResponse, error)
	// Queries publisher by index/address.
	PublisherByIndex(ctx context.Context, in *QueryPublisherByIndexRequest, opts ...grpc.CallOption) (*QueryPublisherByIndexResponse, error)
	// Queries a list of Article items.
	AllArticles(ctx context.Context, in *QueryAllArticlesRequest, opts ...grpc.CallOption) (*QueryAllArticlesResponse, error)
	// Queries a list of AllAnonArticlesCounters items.
	AllAnonArticlesCounters(ctx context.Context, in *QueryAllAnonArticlesCountersRequest, opts ...grpc.CallOption) (*QueryAllAnonArticlesCountersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/bze.cointrunk.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AcceptedDomain(ctx context.Context, in *QueryAcceptedDomainRequest, opts ...grpc.CallOption) (*QueryAcceptedDomainResponse, error) {
	out := new(QueryAcceptedDomainResponse)
	err := c.cc.Invoke(ctx, "/bze.cointrunk.v1.Query/AcceptedDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Publisher(ctx context.Context, in *QueryPublisherRequest, opts ...grpc.CallOption) (*QueryPublisherResponse, error) {
	out := new(QueryPublisherResponse)
	err := c.cc.Invoke(ctx, "/bze.cointrunk.v1.Query/Publisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PublisherByIndex(ctx context.Context, in *QueryPublisherByIndexRequest, opts ...grpc.CallOption) (*QueryPublisherByIndexResponse, error) {
	out := new(QueryPublisherByIndexResponse)
	err := c.cc.Invoke(ctx, "/bze.cointrunk.v1.Query/PublisherByIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllArticles(ctx context.Context, in *QueryAllArticlesRequest, opts ...grpc.CallOption) (*QueryAllArticlesResponse, error) {
	out := new(QueryAllArticlesResponse)
	err := c.cc.Invoke(ctx, "/bze.cointrunk.v1.Query/AllArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllAnonArticlesCounters(ctx context.Context, in *QueryAllAnonArticlesCountersRequest, opts ...grpc.CallOption) (*QueryAllAnonArticlesCountersResponse, error) {
	out := new(QueryAllAnonArticlesCountersResponse)
	err := c.cc.Invoke(ctx, "/bze.cointrunk.v1.Query/AllAnonArticlesCounters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of AcceptedDomain items.
	AcceptedDomain(context.Context, *QueryAcceptedDomainRequest) (*QueryAcceptedDomainResponse, error)
	// Queries a list of Publisher items.
	Publisher(context.Context, *QueryPublisherRequest) (*QueryPublisherResponse, error)
	// Queries publisher by index/address.
	PublisherByIndex(context.Context, *QueryPublisherByIndexRequest) (*QueryPublisherByIndexResponse, error)
	// Queries a list of Article items.
	AllArticles(context.Context, *QueryAllArticlesRequest) (*QueryAllArticlesResponse, error)
	// Queries a list of AllAnonArticlesCounters items.
	AllAnonArticlesCounters(context.Context, *QueryAllAnonArticlesCountersRequest) (*QueryAllAnonArticlesCountersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AcceptedDomain(ctx context.Context, req *QueryAcceptedDomainRequest) (*QueryAcceptedDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptedDomain not implemented")
}
func (*UnimplementedQueryServer) Publisher(ctx context.Context, req *QueryPublisherRequest) (*QueryPublisherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publisher not implemented")
}
func (*UnimplementedQueryServer) PublisherByIndex(ctx context.Context, req *QueryPublisherByIndexRequest) (*QueryPublisherByIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublisherByIndex not implemented")
}
func (*UnimplementedQueryServer) AllArticles(ctx context.Context, req *QueryAllArticlesRequest) (*QueryAllArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllArticles not implemented")
}
func (*UnimplementedQueryServer) AllAnonArticlesCounters(ctx context.Context, req *QueryAllAnonArticlesCountersRequest) (*QueryAllAnonArticlesCountersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllAnonArticlesCounters not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bze.cointrunk.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AcceptedDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAcceptedDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AcceptedDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bze.cointrunk.v1.Query/AcceptedDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AcceptedDomain(ctx, req.(*QueryAcceptedDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Publisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Publisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bze.cointrunk.v1.Query/Publisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Publisher(ctx, req.(*QueryPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PublisherByIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPublisherByIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PublisherByIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bze.cointrunk.v1.Query/PublisherByIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PublisherByIndex(ctx, req.(*QueryPublisherByIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bze.cointrunk.v1.Query/AllArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllArticles(ctx, req.(*QueryAllArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllAnonArticlesCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAnonArticlesCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllAnonArticlesCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bze.cointrunk.v1.Query/AllAnonArticlesCounters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllAnonArticlesCounters(ctx, req.(*QueryAllAnonArticlesCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bze.cointrunk.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AcceptedDomain",
			Handler:    _Query_AcceptedDomain_Handler,
		},
		{
			MethodName: "Publisher",
			Handler:    _Query_Publisher_Handler,
		},
		{
			MethodName: "PublisherByIndex",
			Handler:    _Query_PublisherByIndex_Handler,
		},
		{
			MethodName: "AllArticles",
			Handler:    _Query_AllArticles_Handler,
		},
		{
			MethodName: "AllAnonArticlesCounters",
			Handler:    _Query_AllAnonArticlesCounters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bze/cointrunk/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAcceptedDomainRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAcceptedDomainRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAcceptedDomainRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAcceptedDomainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAcceptedDomainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAcceptedDomainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AcceptedDomain) > 0 {
		for iNdEx := len(m.AcceptedDomain) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AcceptedDomain[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPublisherRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPublisherRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPublisherRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPublisherResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPublisherResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPublisherResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Publisher) > 0 {
		for iNdEx := len(m.Publisher) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Publisher[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPublisherByIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPublisherByIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPublisherByIndexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPublisherByIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPublisherByIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPublisherByIndexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Publisher.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllArticlesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllArticlesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllArticlesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllArticlesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllArticlesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllArticlesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Article) > 0 {
		for iNdEx := len(m.Article) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Article[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAnonArticlesCountersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAnonArticlesCountersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAnonArticlesCountersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAnonArticlesCountersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAnonArticlesCountersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAnonArticlesCountersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AnonArticlesCounters) > 0 {
		for iNdEx := len(m.AnonArticlesCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AnonArticlesCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAcceptedDomainRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAcceptedDomainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AcceptedDomain) > 0 {
		for _, e := range m.AcceptedDomain {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPublisherRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPublisherResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Publisher) > 0 {
		for _, e := range m.Publisher {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPublisherByIndexRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPublisherByIndexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Publisher.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllArticlesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllArticlesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Article) > 0 {
		for _, e := range m.Article {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAnonArticlesCountersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAnonArticlesCountersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AnonArticlesCounters) > 0 {
		for _, e := range m.AnonArticlesCounters {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAcceptedDomainRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAcceptedDomainRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAcceptedDomainRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAcceptedDomainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAcceptedDomainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAcceptedDomainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedDomain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedDomain = append(m.AcceptedDomain, AcceptedDomain{})
			if err := m.AcceptedDomain[len(m.AcceptedDomain)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPublisherRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPublisherRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPublisherRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPublisherResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPublisherResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPublisherResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Publisher", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Publisher = append(m.Publisher, Publisher{})
			if err := m.Publisher[len(m.Publisher)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPublisherByIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPublisherByIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPublisherByIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPublisherByIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPublisherByIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPublisherByIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Publisher", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Publisher.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllArticlesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllArticlesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllArticlesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllArticlesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllArticlesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllArticlesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Article", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Article = append(m.Article, Article{})
			if err := m.Article[len(m.Article)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAnonArticlesCountersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAnonArticlesCountersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAnonArticlesCountersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAnonArticlesCountersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAnonArticlesCountersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAnonArticlesCountersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnonArticlesCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnonArticlesCounters = append(m.AnonArticlesCounters, AnonArticlesCounter{})
			if err := m.AnonArticlesCounters[len(m.AnonArticlesCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
