// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bze/burner/v2/tx.proto

package v2types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgFundBurner struct {
	Creator string                                   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgFundBurner) Reset()         { *m = MsgFundBurner{} }
func (m *MsgFundBurner) String() string { return proto.CompactTextString(m) }
func (*MsgFundBurner) ProtoMessage()    {}
func (*MsgFundBurner) Descriptor() ([]byte, []int) {
	return fileDescriptor_66dda2a3617d3a66, []int{0}
}
func (m *MsgFundBurner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundBurner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundBurner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundBurner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundBurner.Merge(m, src)
}
func (m *MsgFundBurner) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundBurner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundBurner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundBurner proto.InternalMessageInfo

func (m *MsgFundBurner) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgFundBurner) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgFundBurnerResponse struct {
}

func (m *MsgFundBurnerResponse) Reset()         { *m = MsgFundBurnerResponse{} }
func (m *MsgFundBurnerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFundBurnerResponse) ProtoMessage()    {}
func (*MsgFundBurnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66dda2a3617d3a66, []int{1}
}
func (m *MsgFundBurnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundBurnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundBurnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundBurnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundBurnerResponse.Merge(m, src)
}
func (m *MsgFundBurnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundBurnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundBurnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundBurnerResponse proto.InternalMessageInfo

type MsgStartRaffle struct {
	Creator     string                      `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Pot         cosmossdk_io_math.Int       `protobuf:"bytes,2,opt,name=pot,proto3,customtype=cosmossdk.io/math.Int" json:"pot"`
	Duration    uint64                      `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Chances     uint64                      `protobuf:"varint,4,opt,name=chances,proto3" json:"chances,omitempty"`
	Ratio       cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=ratio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"ratio"`
	TicketPrice cosmossdk_io_math.Int       `protobuf:"bytes,6,opt,name=ticket_price,json=ticketPrice,proto3,customtype=cosmossdk.io/math.Int" json:"ticket_price"`
	Denom       string                      `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *MsgStartRaffle) Reset()         { *m = MsgStartRaffle{} }
func (m *MsgStartRaffle) String() string { return proto.CompactTextString(m) }
func (*MsgStartRaffle) ProtoMessage()    {}
func (*MsgStartRaffle) Descriptor() ([]byte, []int) {
	return fileDescriptor_66dda2a3617d3a66, []int{2}
}
func (m *MsgStartRaffle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartRaffle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartRaffle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartRaffle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartRaffle.Merge(m, src)
}
func (m *MsgStartRaffle) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartRaffle) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartRaffle.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartRaffle proto.InternalMessageInfo

func (m *MsgStartRaffle) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgStartRaffle) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MsgStartRaffle) GetChances() uint64 {
	if m != nil {
		return m.Chances
	}
	return 0
}

func (m *MsgStartRaffle) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type MsgStartRaffleResponse struct {
}

func (m *MsgStartRaffleResponse) Reset()         { *m = MsgStartRaffleResponse{} }
func (m *MsgStartRaffleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgStartRaffleResponse) ProtoMessage()    {}
func (*MsgStartRaffleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66dda2a3617d3a66, []int{3}
}
func (m *MsgStartRaffleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgStartRaffleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgStartRaffleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgStartRaffleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgStartRaffleResponse.Merge(m, src)
}
func (m *MsgStartRaffleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgStartRaffleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgStartRaffleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgStartRaffleResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgFundBurner)(nil), "bze.burner.v2.MsgFundBurner")
	proto.RegisterType((*MsgFundBurnerResponse)(nil), "bze.burner.v2.MsgFundBurnerResponse")
	proto.RegisterType((*MsgStartRaffle)(nil), "bze.burner.v2.MsgStartRaffle")
	proto.RegisterType((*MsgStartRaffleResponse)(nil), "bze.burner.v2.MsgStartRaffleResponse")
}

func init() { proto.RegisterFile("bze/burner/v2/tx.proto", fileDescriptor_66dda2a3617d3a66) }

var fileDescriptor_66dda2a3617d3a66 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0xdb, 0x26, 0xa5, 0x57, 0x8a, 0x84, 0xd5, 0x1f, 0x6e, 0x50, 0x9d, 0x28, 0x2c, 0x56,
	0xa5, 0xdc, 0x91, 0x30, 0xd1, 0x09, 0x05, 0x04, 0x42, 0xa2, 0x12, 0x32, 0x1b, 0x4b, 0x75, 0x3e,
	0xbf, 0x3a, 0x56, 0xea, 0x3b, 0xcb, 0x77, 0x8e, 0xda, 0x8c, 0x8c, 0x4c, 0xfc, 0x1d, 0x4c, 0xfd,
	0x0b, 0x98, 0x3b, 0x76, 0x41, 0x42, 0x0c, 0x05, 0x25, 0x43, 0xff, 0x0d, 0xe4, 0xbb, 0x0b, 0x4a,
	0x00, 0x21, 0x96, 0x5c, 0xbe, 0xf7, 0xbd, 0xe7, 0xef, 0x7b, 0x9f, 0x1e, 0xda, 0x8d, 0x26, 0x40,
	0xa2, 0xb2, 0xe0, 0x50, 0x90, 0x71, 0x9f, 0xa8, 0x73, 0x9c, 0x17, 0x42, 0x09, 0x77, 0x2b, 0x9a,
	0x00, 0x36, 0x75, 0x3c, 0xee, 0x37, 0xef, 0xd3, 0x2c, 0xe5, 0x82, 0xe8, 0x5f, 0xd3, 0xd1, 0xdc,
	0x63, 0x42, 0x66, 0x42, 0x92, 0x4c, 0x26, 0x64, 0xdc, 0xab, 0x1e, 0x4b, 0xf8, 0x96, 0x88, 0xa8,
	0x04, 0x32, 0xee, 0x45, 0xa0, 0x68, 0x8f, 0x30, 0x91, 0x72, 0xcb, 0xef, 0x1b, 0xfe, 0x44, 0x23,
	0x62, 0x80, 0xa5, 0xb6, 0x13, 0x91, 0x08, 0x53, 0xaf, 0xfe, 0x99, 0x6a, 0xe7, 0xb3, 0x83, 0xb6,
	0x8e, 0x65, 0xf2, 0xa2, 0xe4, 0xf1, 0x40, 0x3b, 0x72, 0x3d, 0xb4, 0xce, 0x0a, 0xa0, 0x4a, 0x14,
	0x9e, 0xd3, 0x76, 0x82, 0x8d, 0x70, 0x0e, 0x5d, 0x86, 0x1a, 0x34, 0x13, 0x25, 0x57, 0xde, 0x4a,
	0x7b, 0x35, 0xd8, 0xec, 0xef, 0x63, 0x2b, 0x50, 0xb9, 0xc1, 0xd6, 0x0d, 0x7e, 0x26, 0x52, 0x3e,
	0x78, 0x74, 0x75, 0xd3, 0xaa, 0x7d, 0xfa, 0xde, 0x0a, 0x92, 0x54, 0x0d, 0xcb, 0x08, 0x33, 0x91,
	0x59, 0x37, 0xf6, 0xe9, 0xca, 0x78, 0x44, 0xd4, 0x45, 0x0e, 0x52, 0x0f, 0xc8, 0xd0, 0x7e, 0xfa,
	0x08, 0xbf, 0xbf, 0xbd, 0x3c, 0x9c, 0x4b, 0x7e, 0xb8, 0xbd, 0x3c, 0x3c, 0xa8, 0x52, 0x3c, 0x5f,
	0xc8, 0x71, 0xc9, 0x6e, 0x67, 0x0f, 0xed, 0x2c, 0x15, 0x42, 0x90, 0xb9, 0xe0, 0x12, 0x3a, 0x5f,
	0x56, 0xd0, 0xbd, 0x63, 0x99, 0xbc, 0x55, 0xb4, 0x50, 0x21, 0x3d, 0x3d, 0x3d, 0x83, 0x7f, 0xac,
	0x46, 0xd0, 0x6a, 0x2e, 0xaa, 0xbd, 0x9c, 0x60, 0x63, 0x70, 0x50, 0x99, 0xff, 0x76, 0xd3, 0xda,
	0x31, 0x56, 0x65, 0x3c, 0xc2, 0xa9, 0x20, 0x19, 0x55, 0x43, 0xfc, 0x8a, 0xab, 0xb0, 0xea, 0x74,
	0x9b, 0xe8, 0x4e, 0x5c, 0x16, 0x54, 0xa5, 0x82, 0x7b, 0xab, 0x6d, 0x27, 0x58, 0x0b, 0x7f, 0x61,
	0x2d, 0x33, 0xa4, 0x9c, 0x81, 0xf4, 0xd6, 0x34, 0x35, 0x87, 0xee, 0x13, 0x54, 0xd7, 0x3d, 0x5e,
	0x5d, 0x0b, 0x3d, 0xb4, 0x42, 0x0f, 0xfe, 0x14, 0x7a, 0x0d, 0x09, 0x65, 0x17, 0xcf, 0x81, 0x85,
	0x66, 0xc2, 0x7d, 0x8a, 0xee, 0xaa, 0x94, 0x8d, 0x40, 0x9d, 0xe4, 0x45, 0xca, 0xc0, 0x6b, 0xfc,
	0x8f, 0xd5, 0x4d, 0x33, 0xf2, 0xa6, 0x9a, 0x70, 0xb7, 0x51, 0x3d, 0x06, 0x2e, 0x32, 0x6f, 0x5d,
	0xef, 0x6e, 0xc0, 0x11, 0xf9, 0x3d, 0x6f, 0xff, 0x2f, 0x79, 0x2f, 0x84, 0xd8, 0xf1, 0xd0, 0xee,
	0x72, 0x65, 0x9e, 0xf8, 0xe0, 0xe5, 0xd5, 0xd4, 0x77, 0xae, 0xa7, 0xbe, 0xf3, 0x63, 0xea, 0x3b,
	0x1f, 0x67, 0x7e, 0xed, 0x7a, 0xe6, 0xd7, 0xbe, 0xce, 0xfc, 0xda, 0xbb, 0xee, 0xc2, 0x19, 0x44,
	0x13, 0xe8, 0xd2, 0xb3, 0x7c, 0x48, 0x15, 0x50, 0x8d, 0x16, 0xc5, 0xf4, 0x45, 0x44, 0x0d, 0x7d,
	0x9b, 0x8f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x29, 0xef, 0x42, 0x41, 0x03, 0x00, 0x00,
}

func (m *MsgFundBurner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundBurner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundBurner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFundBurnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundBurnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundBurnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgStartRaffle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartRaffle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartRaffle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.TicketPrice.Size()
		i -= size
		if _, err := m.TicketPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Ratio.Size()
		i -= size
		if _, err := m.Ratio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Chances != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Chances))
		i--
		dAtA[i] = 0x20
	}
	if m.Duration != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Pot.Size()
		i -= size
		if _, err := m.Pot.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgStartRaffleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgStartRaffleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgStartRaffleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFundBurner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgFundBurnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgStartRaffle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Pot.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Duration != 0 {
		n += 1 + sovTx(uint64(m.Duration))
	}
	if m.Chances != 0 {
		n += 1 + sovTx(uint64(m.Chances))
	}
	l = m.Ratio.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.TicketPrice.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgStartRaffleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFundBurner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundBurner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundBurner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFundBurnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundBurnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundBurnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartRaffle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartRaffle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartRaffle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chances", wireType)
			}
			m.Chances = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Chances |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ratio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ratio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TicketPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TicketPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgStartRaffleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgStartRaffleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgStartRaffleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
